### ISSUE TITLE
Improve hour manipulation and downtime information

### ISSUE THREAD

**Issue by pvinicius** [thiagoloureiro/AlertHawk.UI#118]
It would be really helpful if I could change the time range on the chart to see when the downtime happened. 
And if you could make the downtime indicator clickable, that would be great, that way, I could go straight to the alert. 

**Downtime indicator**
![image](https://github.com/user-attachments/assets/09cb44c0-ff37-4db9-98ab-3af7eea5e984)

**Example for range manipulation**
https://www.amcharts.com/demos/line-graph/
![image](https://github.com/user-attachments/assets/8012d9e3-d060-43a0-9e16-17eda8795fab)

Best Regards

**Comment by thiagoloureiro** [comment]
Hi Pedro, we're talking here about two different things. 

One is this component:
![image](https://github.com/user-attachments/assets/bacb474f-c453-40c9-9ec3-a16fefbcc5ae)

This one indeed needs improvement, for example, when we change the period from 7 days to 30 days, 6 months, etc, he is not changing.

Another one is the graph, what I had in mind also is to show the graph based on the selected period:

<img width="197" alt="image" src="https://github.com/user-attachments/assets/e69ff7e1-6850-4faf-9b94-2c65ec6ebff1">

and make red dots when it fails:
<img width="756" alt="image" src="https://github.com/user-attachments/assets/2254df01-db0b-45eb-b571-d32b3a82ec86">


if you check the API call, the chart data is there:
<img width="761" alt="image" src="https://github.com/user-attachments/assets/8aaa72de-41be-43db-acfe-8f17b0c1fd32">

where status: true/false shows that is.
We can start with the chart first, to bring more data according to the period selected and make it clickable.
The issue I see is, if we select 6 months the amount of data will be huge to draw, right now we have 60 points per hour.
for 1 day will be 1440 points, 7 days 10080, and so on. We need to test how that will be displayed properly on the UI.

**Comment by pvinicius** [comment]
Downsampling looks a effective approach to solve this case where there are a lot of data, decreasing them and improving the model performance.
I had tested it, doing some test tables and it's clear how it will decrease the data and keeping the information correct.

**Comment by thiagoloureiro** [comment]
@pvinicius will you create a PR for that ?

**Comment by pvinicius** [comment]
> @pvinicius will you create a PR for that ? Feel free to fork and push the changes.

I'm on it, will open PR this afternoon

**Comment by pvinicius** [comment]
@thiagoloureiro look at, it were applied a downsampling with 50sec of interval, the challenge was find the best interval for the metrics filtered. Using as metric 24 hours which there are 1500 points, after applyting downsampling with the same 50 sec of interval, they were reduced from 1437 to 25 points.

This video bellow show how it is working

[downsampling.webm](https://github.com/user-attachments/assets/36169d75-1926-4e3a-9624-760bdab34e64)

by the code perspective I used the downsampling algorithm that you provided also I added two setting properties to manage if downsampling is activated or not.

```
  "Downsampling": {
    "Active": true,
    "IntervalInSeconds": 50
  },
```

**Comment by thiagoloureiro** [comment]
@pvinicius on the 1 hour filter there are only 2 points instead of the number of points (max 60) for the hour? 
<img width="1080" alt="image" src="https://github.com/user-attachments/assets/4be8c66c-b967-4b18-b164-4d3093c23403">


for 24 hours looks ok.  We can connect on that to discuss

**Comment by pvinicius** [comment]
1 hour filter were applied the downsampling as well, grouping all success history in 2 points, I agree that could keep as it was, let's talk about it

**Comment by thiagoloureiro** [comment]
closing it due to be not really doable to finish it right now.
