### ISSUE TITLE
Bug - After creating or deleting the topbar is not updated

### ISSUE THREAD

**Issue by thiagoloureiro** [thiagoloureiro/AlertHawk.UI#121]
Repro Steps:

1. Login to the application
2. Create a new Group
3. Create a new monitor

Check the Top bar:
<img width="921" alt="image" src="https://github.com/user-attachments/assets/3e9fce58-9c6a-450e-8b08-febe13f97db6">

1. Refresh the screen
2. The correct count appears:

<img width="868" alt="image" src="https://github.com/user-attachments/assets/20799077-3487-42a4-ab85-89cb60c7b757">

1. Open the monitor
2. Delete the monitor

After deletion the monitor count on the top is incorrect:

<img width="878" alt="image" src="https://github.com/user-attachments/assets/b4acbff5-e62a-4d4d-a4bb-4ab312e2b642">

**Comment by SandipGyawali** [comment]
@thiagoloureiro is this project open to contribute and explore??

**Comment by thiagoloureiro** [comment]
Yes sir. Sent from my iPhoneOn 20 Oct 2024, at 12:54, Sand1p.gyawa1i (Qrqr30) ***@***.***> wrote:﻿
@thiagoloureiro is this project open to contribute and explore??

**Comment by thiagoloureiro** [comment]
https://github.com/thiagoloureiro/AlertHawk.UI/pull/122
did the trick.:)

**Comment by SandipGyawali** [comment]
@thiagoloureiro can you give some brief explaination about what are you guys working on what you are tyring to build.
